Test macOS
sybrenjansen/mpire pull request #92
Opened 2023-09-18 11:41 UTC by jonashaag

2023-09-18 11:43 UTC, jonashaag commented
The `gc.collect()` calls seem to the fix the semaphore leakage but it feels kind of hacky

2023-09-25 12:54 UTC, sybrenjansen commented
Until I have a mac I cannot test this, unfortunately. I will try to set up a VM in the near future, but I've been quite busy :sweat_smile: 

I can live with the hacky `gc.collect()` for now, but perhaps add a TODO in the code that this is not a proper fix. Additionally, let's remove the `macos` testing on github as other stuff probably won't run successfully yet. 

This PR will at least fix a few things already for mac. Probably enough for people to get started. And when I get time to test it on mac we can add macos properly.

2023-09-25 12:56 UTC, sybrenjansen requested changes

2023-09-25 13:53 UTC, sybrenjansen requested changes
One minor things left. Can you add a line to `docs/changelog.rst` with the changes you made? E.g., added a workaround for semaphore leakage on macOs + fixed a bug when working in a fork context while the system default is spawn. 

You can put it under the `unreleased` section.

2023-09-27 07:24 UTC, sybrenjansen approved these changes

2023-10-02 12:21 UTC, merged